export const HELLO = "Hello👋,";
export const BALANCE = "Balance";
export const TODAY_SPENDS = "Today Spends";
export const TODAY_LIMIT = "Today Limit ";
export const TODAY_STATISTICS = "Today Statistics";
export const SAVINGS = "Savings";
export const SPEND_AMOUNT = "Spend Amount"
export const UPDATE = "Update"
export const SPENDS = "Spends"
export const LIMIT = "Limit"
export const SET_MONTHLY_AMOUNT = "Please enter amount"
export const MONTHLY_AMOUNT_ZERO_DISC = "Your monthly limit is currently set to zero. Please configure your monthly amount.";
export const AMOOUNT_ERROR = "Wrong Amount!"
export const MONTH_AMOUNT_LIMIT = "Please enter amount above 500"
export const VIEW_MORE =  "View more"
export const TRANSACTION_HISTORY = "transaction history"
export const S_NO = "S No"
export const AMOUNT = 'Amount'
export const DATE = "Date"
export const RESPONSE = "Response"
export const NO_DATA_FOUND = "No data found!"
export const GROCERY = "Grocery"
export const DEFAULT = "Default"
export const NORMAL = 'Normal'
export const SPEND_TYPE = "Spend Type"
export const AMOUNT_ERROR = "Please enter Amount!"
export const WELCOME = "Welcome Back🤩"
export const LOGIN_TO_YOUR_ACCOUNT = "Login into your account"
export const USER_NAME = "User name or Email"
export const PASSWORD = "Password"
export const LOGIN = "Login"
export const SIGN_UP = "Sign Up"
export const TROUBLE_IN_LOGIN = "Trouble on Login ?"
export const RESET_PASSWORD = "Reset Password"