export const HELLO = "Hello👋,";
export const BALANCE = "Balance";
export const TODAY_SPENDS = "Today Spends";
export const TODAY_LIMIT = "Today Limit ";
export const TODAY_STATISTICS = "Today Statistics";
export const SAVINGS = "Savings";
export const SPEND_AMOUNT = "Spend Amount";
export const UPDATE = "Update";
export const SPENDS = "Spends";
export const LIMIT = "Limit";
export const SET_MONTHLY_AMOUNT = "Please enter amount";
export const MONTHLY_AMOUNT_ZERO_DISC =
  "Your monthly limit is currently set to zero. Please configure your monthly amount.";
export const AMOOUNT_ERROR = "Wrong Amount!";
export const MONTH_AMOUNT_LIMIT = "Please enter amount above 500";
export const VIEW_MORE = "View more";
export const TRANSACTION_HISTORY = "transaction history";
export const S_NO = "S No";
export const AMOUNT = "Amount";
export const DATE = "Date";
export const RESPONSE = "Response";
export const NO_DATA_FOUND = "No data found!";
export const GROCERY = "Grocery";
export const DEFAULT = "Default";
export const NORMAL = "Normal";
export const SPEND_TYPE = "Spend Type";
export const AMOUNT_ERROR = "Please enter Amount!";
export const WELCOME = "Welcome Back🤩";
export const LOGIN_TO_YOUR_ACCOUNT = "Login into your account";
export const USER_NAME = "Email Id";
export const PASSWORD = "Password";
export const LOGIN = "Login";
export const SIGN_UP = "Sign Up";
export const TROUBLE_IN_LOGIN = "Trouble on Login ?";
export const RESET_PASSWORD = "Reset Password";
export const USER_NAME_ERROR = "Please enter Email Id";
export const PASSWORD_ERROR = "Please enter Password";
export const CREATE_ACCOUNT = "Create Account";
export const LAREADY__HAVE_ACCOUNT = "Already have a account?";
export const FIRST_NAME = "First Name";
export const FIRST_NAME_ERROR = "Please enter First Name";
export const LAST_NAME = "Last Name";
export const EMAIL_ID_ERROR = "Please enter Email Id";
export const EMAIL_ID = "Email Id";
export const MOBILE_NUMBER = "Mobile Number";
export const PASSWORD_DONT_MATCH = "Passwords does't match";
export const OTP = "OTP";
export const OPT_DONT_MATCH = "Wrong OTP entered";
export const NEXT = "Next";
export const INVALID_EMAIL_ID = "Invalid Email Id";
export const INVALID_OTP = "Invalid Otp";
export const ACCOUNT_CREATED_SUCCESS = "Account created successfully";
export const OTP_SEND_SUCCESS = "Otp send successfully";
export const BACK = "Back";
export const LOGGED_IN_SUCCESS = "Logged in successfully";
export const ENTER_MONTHLY_CHARGES = "Please enter your monthly charges."
export const ENTER_MONTHLY_GROCERY_AMOUNT = "Please enter your monthly grocery amount"
export const ENTER_MONTHLY_EXTRA_SPENDS = "Please enter your monthly extra spends"
export const AMOUNT_SET_SUCCESS = 'Monthly amount configured'
export const CHARGES = "Charges"
export const SELECT_GROCERYS = "Select your grocerys"
export const ITEM_FVM = "Enter your item"
export const PRICE_FVM = "Enter item price"
export const GMSPER_WEEK_FVM = "Enter gms per Week"
export const DATE_FVM = "Enter your date"
export const ITEM_ADDED_SUCCESSFULLY = "Item added successfully"
export const  ITEM_ADDED_FAILED = "Item added failed please try again"
export const ADD_ITEM = "Add item"
export const SUBMIT = "Submit"
export const CLOSE = "Close"
export const ADD_GROCERY_ITEM = "Add grocery item"
export const ADD = "Add"
export const ITEM_NAME = "Item name"
export const PRICE = "Price"
export const GMS = "Gms"
export const COMPLETED = "Completed"
export const MISSED = "Missed"
export const REQUEST_SUCCESS = "Completed Success"