export const HELLO = "Hello👋,";
export const BALANCE = "Balance";
export const TODAY_SPENDS = "Today Spends";
export const TODAY_LIMIT = "Today Limit ";
export const TODAY_STATISTICS = "Today Statistics";
export const SAVINGS = "Savings";
export const SPEND_AMOUNT = "Spend Amount"
export const UPDATE = "Update"
export const SPENDS = "Spends"
export const LIMIT = "Limit"
export const SET_MONTHLY_AMOUNT = "Please enter amount"
export const MONTHLY_AMOUNT_ZERO_DISC = "Your monthly limit is currently set to zero. Please configure your monthly amount.";
export const AMOOUNT_ERROR = "Wrong Amount!"
export const MONTH_AMOUNT_LIMIT = "Please enter amount above 500"
export const VIEW_MORE =  "View more"
export const TRANSACTION_HISTORY = "transaction history"
export const S_NO = "S No"
export const AMOUNT = 'Amount'
export const DATE = "Date"
export const RESPONSE = "Response"
export const NO_DATA_FOUND = "No data found!"
export const GROCERY = "Grocery"
export const DEFAULT = "Default"